version: "3"

services:
  golang:
    tty: true
    build: "."
    volumes:
      - ./app:/go/src/github.com/nginx_go/app
    ports:
      - "3000"
    command: bash -c "cd app && go run main.go"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - "golang"